<a href="https://colab.research.google.com/github/RutikaChougule/Books-Python/blob/main/PythonCourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DataType

In [ ]:
x='true'
type(x)

str

In [ ]:
z=True
type(z)

bool

In [ ]:
e='Analytics'
e

'Analytics'

List Datatype
Index start from zero

In [ ]:
sample_list=[1,13.6,"hi",12]
sample_list

[1, 13.6, 'hi', 12]

In [ ]:
type(sample_list)

list

List is Mutable

In [ ]:
sample_list[0]=10
sample_list

[10, 13.6, 'hi', 12]

Tuple

In [ ]:
s_tuple=1,3,'ru',34.5
type(s_tuple)

tuple

Numpy Library

In [5]:
import numpy as np


In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [8]:
np.random.rand(3,2)

array([[0.41803809, 0.21890927],
       [0.79849549, 0.42485063],
       [0.60498193, 0.82119439]])

In [10]:
np.random.randint(1,5)

2

sample_array=np.arange(30)
sample_array

In [13]:
rand_array=np.random.randint(0,100,20)
rand_array

array([12, 14, 83, 54, 20, 78, 31, 17, 75, 90, 78, 38, 73, 50, 85, 91, 40,
       36, 70, 31])

In [15]:
rand_array.min()

12

In [17]:
rand_array.argmin()

0

In [19]:
a=np.random.rand(2,3)
a

array([[0.39328068, 0.92653375, 0.15020188],
       [0.53888246, 0.57775811, 0.77884896]])

In [20]:
a.T

array([[0.39328068, 0.53888246],
       [0.92653375, 0.57775811],
       [0.15020188, 0.77884896]])

In [21]:
sample_array[3]

3

In [22]:
sample_array[3:7]

array([3, 4, 5, 6])

In [33]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [32]:
sample_array[:]
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

Two Dimensional Array

In [35]:
import numpy as np


In [36]:
sample_mat=np.array([[50,20,1,33],[3,6,8,37],[4,9,2,34]])
sample_mat

array([[50, 20,  1, 33],
       [ 3,  6,  8, 37],
       [ 4,  9,  2, 34]])

In [42]:
sample_mat[0:3,1]
sample_mat[0:3,2]
sample_mat[0:3,3]

array([33, 37, 34])

In [43]:
sample_mat[2,:]

array([ 4,  9,  2, 34])

In [44]:

sample_mat.T

array([[50,  3,  4],
       [20,  6,  9],
       [ 1,  8,  2],
       [33, 37, 34]])

In [45]:
sample_mat[2,:]

array([ 4,  9,  2, 34])

In [47]:
sample_mat[:,(3,0)]

array([[33, 50],
       [37,  3],
       [34,  4]])

In [48]:
sample_array=np.arange(1,20)

In [49]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [50]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [51]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [52]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [53]:
np.max(sample_array)

19

In [54]:
np.std(sample_array)

5.477225575051661

In [55]:
np.var(sample_array)

30.0